import type { Language } from "@/lib/translations"

export interface CaseStudy {
  slug: string
  image: string
  projectUrl: string
  title: string
  shortDescription: string
  industry: string
  about: string
  clientDoes: string
  problem: string
  solution: string
  built: string[]
  services: string[]
  duration: string
  results: Array<{
    value: string
    label: string
  }>
}

const caseStudies: Record<Language, CaseStudy[]> = {
  en: [
    {
      slug: "sviuryst-law-firm",
      image: "/project-law.jpg",
      projectUrl: "https://www.advokats24.com.ua/",
      title: "Sviuryst Law Firm",
      shortDescription: "Conversion-optimized legal website with streamlined consultation funnels and organic lead capture.",
      industry: "Legal Services",
      about: "Sviuryst is a full-service law firm providing legal representation, urgent legal support, and business consulting.",
      clientDoes: "They deliver legal consulting, court representation, and contract services for private individuals and corporate clients.",
      problem: "The previous website generated low-quality leads, failed to establish credibility, and produced inconsistent consultation requests.",
      solution: "We redesigned the entire user journey around trust signals, clear service positioning, and frictionless consultation booking.",
      built: ["Conversion-optimized service pages", "High-intent lead capture forms", "Mobile-first responsive design", "SEO-structured content architecture"],
      services: ["UI/UX Design", "Web Development", "SEO Optimization", "Conversion Rate Optimization"],
      duration: "8 months",
      results: [
        { value: "+230%", label: "Client Growth" },
        { value: "+180%", label: "Lead Volume" },
        { value: "+65%", label: "Conversion Rate" },
      ],
    },
    {
      slug: "oratorica-language-school",
      image: "/project-education.jpg",
      projectUrl: "https://www.oratorica.ua/",
      title: "Oratorica Language School",
      shortDescription: "Automated enrollment platform driving student acquisition and scaling online course sales.",
      industry: "Education",
      about: "Oratorica is a language school offering online and in-person language programs for adults and children.",
      clientDoes: "They provide structured language courses, instructor-led programs, and flexible enrollment options for diverse learners.",
      problem: "Manual enrollment processing created bottlenecks, limiting the ability to scale paid traffic and application volume.",
      solution: "We built a fully automated acquisition system with self-service enrollment and clear conversion-focused user journeys.",
      built: ["End-to-end enrollment automation", "Course-specific landing funnels", "Integrated payment processing", "CRM-ready lead routing"],
      services: ["Web Development", "Business Automation", "Payment Integration", "Growth-Focused UX"],
      duration: "10 months",
      results: [
        { value: "EUR 200K+", label: "Revenue Generated" },
        { value: "+150%", label: "Student Enrollment" },
        { value: "+300%", label: "Applications" },
      ],
    },
    {
      slug: "lurssen-yachts",
      image: "/project-luerssen.jpg",
      projectUrl: "https://www.lurssen.com/",
      title: "Lurssen Yachts",
      shortDescription: "Premium digital experience positioning the brand for investor confidence and high-value client acquisition.",
      industry: "Luxury Yachting",
      about: "Lurssen is a world-renowned superyacht builder serving ultra-high-net-worth individuals and institutional investors globally.",
      clientDoes: "They design and construct bespoke luxury superyachts for private owners, families, and investment groups.",
      problem: "The digital presence failed to communicate brand exclusivity and convert premium traffic into qualified inquiries.",
      solution: "We crafted a premium storytelling experience with refined engagement pathways and strategic intent capture mechanisms.",
      built: ["Immersive visual storytelling", "Investor-focused content architecture", "Performance-optimized media delivery", "Premium inquiry pathways"],
      services: ["UI/UX Design", "Web Development", "Content Strategy", "Performance Optimization"],
      duration: "6 months",
      results: [
        { value: "+70%", label: "Investor Engagement" },
        { value: "+220%", label: "Traffic Growth" },
        { value: "+40%", label: "Qualified Leads" },
      ],
    },
    {
      slug: "sr-aerospace",
      image: "/project-isar-aerospace.jpg",
      projectUrl: "https://isaraerospace.com/",
      title: "SR Aerospace",
      shortDescription: "B2B aerospace platform engineered for partnership development, credibility, and investment growth.",
      industry: "Aerospace & Defense",
      about: "SR Aerospace develops next-generation launch systems and maintains strategic partnerships with industrial leaders.",
      clientDoes: "They secure investment funding, manage industrial partnerships, and demonstrate cutting-edge launch technology capabilities.",
      problem: "The existing digital experience failed to instill investor confidence and convert partnership opportunities effectively.",
      solution: "We rebuilt the platform around proof points, strategic messaging, and enterprise-grade lead generation infrastructure.",
      built: ["B2B-optimized information architecture", "Investment narrative design", "Partnership conversion flows", "Scalable technical frontend"],
      services: ["Web Development", "B2B User Experience", "Technical SEO", "Digital Strategy"],
      duration: "12 months",
      results: [
        { value: "$500M+", label: "Investment Secured" },
        { value: "+35%", label: "Partnership Deals" },
        { value: "+120%", label: "B2B Lead Volume" },
      ],
    },
    {
      slug: "provident-law-llp",
      image: "/project-provident-law.jpg",
      projectUrl: "https://providentlawllp.ca",
      title: "Provident Law LLP",
      shortDescription: "SEO-driven legal platform built to capture organic demand and convert visitors into consultations.",
      industry: "Legal Services",
      about: "Provident Law LLP is a multi-practice legal firm serving individuals and businesses across diverse legal matters.",
      clientDoes: "They provide comprehensive legal consultation, defense representation, and structured legal support services.",
      problem: "Significant organic traffic potential remained untapped, and site visitor-to-consultation conversion rates were critically low.",
      solution: "We restructured content around search intent, streamlined contact pathways, and improved service discoverability across the site.",
      built: ["SEO-optimized service hubs", "Conversion-focused practice area pages", "Mobile-optimized user experience", "Intuitive navigation architecture"],
      services: ["SEO Optimization", "Web Development", "Information Architecture", "Conversion UX"],
      duration: "9 months",
      results: [
        { value: "5000+", label: "Clients Acquired" },
        { value: "+90%", label: "Conversion Rate" },
        { value: "+200%", label: "Organic Traffic" },
      ],
    },
    {
      slug: "real-club-nautico-barcelona",
      image: "/project-rcnb.jpg",
      projectUrl: "https://www.rcnb.com/en/",
      title: "Real Club Nautico de Barcelona",
      shortDescription: "Membership and booking growth platform for a prestigious international yacht club.",
      industry: "Sports & Hospitality",
      about: "RCNB is one of Barcelona's premier yacht clubs, managing memberships, marina services, and international sailing events.",
      clientDoes: "They offer exclusive club memberships, marina berth bookings, and host prestigious international nautical competitions.",
      problem: "The previous website failed to efficiently convert event interest into memberships and booking transactions.",
      solution: "We redesigned member and visitor journeys with clear action paths and trust-building content throughout the experience.",
      built: ["Membership conversion funnels", "Booking-first user journeys", "Event showcase architecture", "Mobile-first UX design"],
      services: ["UI/UX Design", "Web Development", "Conversion Optimization", "Content Strategy"],
      duration: "7 months",
      results: [
        { value: "+85%", label: "Membership Growth" },
        { value: "+140%", label: "Booking Volume" },
        { value: "+160%", label: "User Engagement" },
      ],
    },
  ],
  uk: [
    {
      slug: "sviuryst-law-firm",
      image: "/project-law.jpg",
      projectUrl: "https://www.advokats24.com.ua/",
      title: "Адвокатське бюро «Свій Юрист»",
      shortDescription: "Конверсійний сайт для юридичної практики з оптимізованими воронками консультацій та залученням органічних лідів.",
      industry: "Юридичні послуги",
      about: "«Свій Юрист» — адвокатське бюро повного циклу, що надає юридичне представництво, термінову правову допомогу та бізнес-консалтинг.",
      clientDoes: "Надають юридичні консультації, представництво в суді та договірні послуги для приватних осіб і корпоративних клієнтів.",
      problem: "Попередній сайт генерував низькоякісні ліди, не формував довіру та давав нестабільний потік звернень на консультації.",
      solution: "Ми перепроєктували весь шлях користувача навколо сигналів довіри, чіткого позиціонування послуг та спрощеного запису на консультацію.",
      built: ["Конверсійні сторінки послуг", "Форми захоплення лідів з високим наміром", "Mobile-first адаптивний дизайн", "SEO-структурована архітектура контенту"],
      services: ["UI/UX Дизайн", "Веб-розробка", "SEO-оптимізація", "Оптимізація конверсії"],
      duration: "8 місяців",
      results: [
        { value: "+230%", label: "Зростання клієнтів" },
        { value: "+180%", label: "Обсяг лідів" },
        { value: "+65%", label: "Конверсія" },
      ],
    },
    {
      slug: "oratorica-language-school",
      image: "/project-education.jpg",
      projectUrl: "https://www.oratorica.ua/",
      title: "Oratorica — Школа мов",
      shortDescription: "Автоматизована платформа реєстрації для залучення студентів та масштабування продажів онлайн-курсів.",
      industry: "Освіта",
      about: "Oratorica — мовна школа, що пропонує онлайн та офлайн програми вивчення мов для дорослих і дітей.",
      clientDoes: "Надають структуровані мовні курси, програми з викладачами та гнучкі варіанти реєстрації для різних категорій студентів.",
      problem: "Ручна обробка реєстрацій створювала вузькі місця, обмежуючи можливість масштабування платного трафіку та обсягу заявок.",
      solution: "Ми побудували повністю автоматизовану систему залучення з самообслуговуванням при реєстрації та чіткими конверсійними воронками.",
      built: ["Наскрізна автоматизація реєстрації", "Посадкові воронки для окремих курсів", "Інтегрована обробка платежів", "CRM-ready маршрутизація лідів"],
      services: ["Веб-розробка", "Автоматизація бізнесу", "Інтеграція платежів", "Growth-орієнтований UX"],
      duration: "10 місяців",
      results: [
        { value: "EUR 200K+", label: "Згенерований дохід" },
        { value: "+150%", label: "Реєстрація студентів" },
        { value: "+300%", label: "Заявки" },
      ],
    },
    {
      slug: "lurssen-yachts",
      image: "/project-luerssen.jpg",
      projectUrl: "https://www.lurssen.com/",
      title: "Lurssen Yachts",
      shortDescription: "Преміальний цифровий досвід для позиціонування бренду, зміцнення довіри інвесторів та залучення клієнтів класу HNW.",
      industry: "Люксові яхти",
      about: "Lurssen — всесвітньо відомий виробник суперяхт, що обслуговує ультразаможних приватних клієнтів та інституційних інвесторів по всьому світу.",
      clientDoes: "Проєктують та будують ексклюзивні люксові суперяхти для приватних власників, сімей та інвестиційних груп.",
      problem: "Цифрова присутність не передавала ексклюзивність бренду та не конвертувала преміум-трафік у кваліфіковані запити.",
      solution: "Ми створили преміальний storytelling-досвід з вишуканими шляхами залучення та стратегічними механізмами захоплення намірів.",
      built: ["Імерсивний візуальний сторітелінг", "Контент-архітектура для інвесторів", "Оптимізована доставка медіа", "Преміум-воронки запитів"],
      services: ["UI/UX Дизайн", "Веб-розробка", "Контент-стратегія", "Оптимізація продуктивності"],
      duration: "6 місяців",
      results: [
        { value: "+70%", label: "Залученість інвесторів" },
        { value: "+220%", label: "Зростання трафіку" },
        { value: "+40%", label: "Кваліфіковані ліди" },
      ],
    },
    {
      slug: "sr-aerospace",
      image: "/project-isar-aerospace.jpg",
      projectUrl: "https://isaraerospace.com/",
      title: "SR Aerospace",
      shortDescription: "B2B аерокосмічна платформа для розвитку партнерств, зміцнення довіри та залучення інвестицій.",
      industry: "Аерокосмічна галузь",
      about: "SR Aerospace розробляє системи запуску нового покоління та підтримує стратегічні партнерства з промисловими лідерами.",
      clientDoes: "Залучають інвестиційне фінансування, керують промисловими партнерствами та демонструють передові технології запуску.",
      problem: "Існуючий цифровий досвід не формував довіру інвесторів та не ефективно конвертував партнерські можливості.",
      solution: "Ми перебудували платформу навколо доказів, стратегічних повідомлень та інфраструктури генерації enterprise-лідів.",
      built: ["B2B-оптимізована інформаційна архітектура", "Наративний дизайн для інвесторів", "Партнерські конверсійні потоки", "Масштабований технічний фронтенд"],
      services: ["Веб-розробка", "B2B User Experience", "Технічне SEO", "Цифрова стратегія"],
      duration: "12 місяців",
      results: [
        { value: "$500M+", label: "Залучені інвестиції" },
        { value: "+35%", label: "Партнерські угоди" },
        { value: "+120%", label: "B2B ліди" },
      ],
    },
    {
      slug: "provident-law-llp",
      image: "/project-provident-law.jpg",
      projectUrl: "https://providentlawllp.ca",
      title: "Provident Law LLP",
      shortDescription: "SEO-орієнтована юридична платформа для захоплення органічного попиту та конверсії відвідувачів у консультації.",
      industry: "Юридичні послуги",
      about: "Provident Law LLP — юридична фірма з багатьма практиками, що обслуговує приватних осіб та бізнес у різноманітних правових питаннях.",
      clientDoes: "Надають комплексні юридичні консультації, захист у суді та структуровані послуги правової підтримки.",
      problem: "Значний потенціал органічного трафіку залишався невикористаним, а конверсія відвідувачів у консультації була критично низькою.",
      solution: "Ми реструктурували контент навколо пошукових намірів, оптимізували шляхи контакту та покращили знаходження послуг по всьому сайту.",
      built: ["SEO-оптимізовані хаби послуг", "Конверсійні сторінки практик", "Мобільно-оптимізований UX", "Інтуїтивна архітектура навігації"],
      services: ["SEO-оптимізація", "Веб-розробка", "Інформаційна архітектура", "Конверсійний UX"],
      duration: "9 місяців",
      results: [
        { value: "5000+", label: "Залучених клієнтів" },
        { value: "+90%", label: "Конверсія" },
        { value: "+200%", label: "Органічний трафік" },
      ],
    },
    {
      slug: "real-club-nautico-barcelona",
      image: "/project-rcnb.jpg",
      projectUrl: "https://www.rcnb.com/en/",
      title: "Real Club Nautico de Barcelona",
      shortDescription: "Платформа зростання членства та бронювань для престижного міжнародного яхт-клубу.",
      industry: "Спорт та гостинність",
      about: "RCNB — один з провідних яхт-клубів Барселони, що керує членством, послугами марини та міжнародними вітрильними подіями.",
      clientDoes: "Пропонують ексклюзивне членство в клубі, бронювання причалів та проводять престижні міжнародні морські змагання.",
      problem: "Попередній сайт не ефективно конвертував інтерес до подій у членство та бронювання.",
      solution: "Ми перепроєктували шляхи членів та відвідувачів з чіткими діями та контентом, що будує довіру на всьому досвіді.",
      built: ["Воронки конверсії членства", "User journeys з фокусом на бронювання", "Архітектура презентації подій", "Mobile-first UX дизайн"],
      services: ["UI/UX Дизайн", "Веб-розробка", "Оптимізація конверсії", "Контент-стратегія"],
      duration: "7 місяців",
      results: [
        { value: "+85%", label: "Зростання членства" },
        { value: "+140%", label: "Обсяг бронювань" },
        { value: "+160%", label: "Залученість користувачів" },
      ],
    },
  ],
  ru: [
    {
      slug: "sviuryst-law-firm",
      image: "/project-law.jpg",
      projectUrl: "https://www.advokats24.com.ua/",
      title: "Адвокатское бюро «Свой Юрист»",
      shortDescription: "Конверсионный сайт для юридической практики с оптимизированными воронками консультаций и привлечением органических лидов.",
      industry: "Юридические услуги",
      about: "«Свой Юрист» — адвокатское бюро полного цикла, предоставляющее юридическое представительство, срочную правовую помощь и бизнес-консалтинг.",
      clientDoes: "Предоставляют юридические консультации, представительство в суде и договорные услуги для частных лиц и корпоративных клиентов.",
      problem: "Предыдущий сайт генерировал низкокачественные лиды, не формировал доверие и давал нестабильный поток обращений на консультации.",
      solution: "Мы перепроектировали весь путь пользователя вокруг сигналов доверия, чёткого позиционирования услуг и упрощённой записи на консультацию.",
      built: ["Конверсионные страницы услуг", "Формы захвата лидов с высоким намерением", "Mobile-first адаптивный дизайн", "SEO-структурированная архитектура контента"],
      services: ["UI/UX Дизайн", "Веб-разработка", "SEO-оптимизация", "Оптимизация конверсии"],
      duration: "8 месяцев",
      results: [
        { value: "+230%", label: "Рост клиентов" },
        { value: "+180%", label: "Объём лидов" },
        { value: "+65%", label: "Конверсия" },
      ],
    },
    {
      slug: "oratorica-language-school",
      image: "/project-education.jpg",
      projectUrl: "https://www.oratorica.ua/",
      title: "Oratorica — Школа языков",
      shortDescription: "Автоматизированная платформа регистрации для привлечения студентов и масштабирования продаж онлайн-курсов.",
      industry: "Образование",
      about: "Oratorica — языковая школа, предлагающая онлайн и офлайн программы изучения языков для взрослых и детей.",
      clientDoes: "Предоставляют структурированные языковые курсы, программы с преподавателями и гибкие варианты регистрации для разных категорий студентов.",
      problem: "Ручная обработка регистраций создавала узкие места, ограничивая возможность масштабирования платного трафика и объёма заявок.",
      solution: "Мы построили полностью автоматизированную систему привлечения с самообслуживанием при регистрации и чёткими конверсионными воронками.",
      built: ["Сквозная автоматизация регистрации", "Посадочные воронки для отдельных курсов", "Интегрированная обработка платежей", "CRM-ready маршрутизация лидов"],
      services: ["Веб-разработка", "Автоматизация бизнеса", "Интеграция платежей", "Growth-ориентированный UX"],
      duration: "10 месяцев",
      results: [
        { value: "EUR 200K+", label: "Сгенерированный доход" },
        { value: "+150%", label: "Регистрация студентов" },
        { value: "+300%", label: "Заявки" },
      ],
    },
    {
      slug: "lurssen-yachts",
      image: "/project-luerssen.jpg",
      projectUrl: "https://www.lurssen.com/",
      title: "Lurssen Yachts",
      shortDescription: "Премиальный цифровой опыт для позиционирования бренда, укрепления доверия инвесторов и привлечения клиентов класса HNW.",
      industry: "Люксовые яхты",
      about: "Lurssen — всемирно известный производитель суперяхт, обслуживающий ультрасостоятельных частных клиентов и институциональных инвесторов по всему миру.",
      clientDoes: "Проектируют и строят эксклюзивные люксовые суперяхты для частных владельцев, семей и инвестиционных групп.",
      problem: "Цифровое присутствие не передавало эксклюзивность бренда и не конвертировало премиум-трафик в квалифицированные запросы.",
      solution: "Мы создали премиальный storytelling-опыт с изысканными путями вовлечения и стратегическими механизмами захвата намерений.",
      built: ["Иммерсивный визуальный сторителлинг", "Контент-архитектура для инвесторов", "Оптимизированная доставка медиа", "Премиум-воронки запросов"],
      services: ["UI/UX Дизайн", "Веб-разработка", "Контент-стратегия", "Оптимизация производительности"],
      duration: "6 месяцев",
      results: [
        { value: "+70%", label: "Вовлечённость инвесторов" },
        { value: "+220%", label: "Рост трафика" },
        { value: "+40%", label: "Квалифицированные лиды" },
      ],
    },
    {
      slug: "sr-aerospace",
      image: "/project-isar-aerospace.jpg",
      projectUrl: "https://isaraerospace.com/",
      title: "SR Aerospace",
      shortDescription: "B2B аэрокосмическая платформа для развития партнёрств, укрепления доверия и привлечения инвестиций.",
      industry: "Аэрокосмическая отрасль",
      about: "SR Aerospace разрабатывает системы запуска нового поколения и поддерживает стратегические партнёрства с промышленными лидерами.",
      clientDoes: "Привлекают инвестиционное финансирование, управляют промышленными партнёрствами и демонстрируют передовые технологии запуска.",
      problem: "Существующий цифровой опыт не формировал доверие инвесторов и не эффективно конвертировал партнёрские возможности.",
      solution: "Мы перестроили платформу вокруг доказательств, стратегических сообщений и инфраструктуры генерации enterprise-лидов.",
      built: ["B2B-оптимизированная информационная архитектура", "Нарративный дизайн для инвесторов", "Партнёрские конверсионные потоки", "Масштабируемый технический фронтенд"],
      services: ["Веб-разработка", "B2B User Experience", "Техническое SEO", "Цифровая стратегия"],
      duration: "12 месяцев",
      results: [
        { value: "$500M+", label: "Привлечённые инвестиции" },
        { value: "+35%", label: "Партнёрские сделки" },
        { value: "+120%", label: "B2B лиды" },
      ],
    },
    {
      slug: "provident-law-llp",
      image: "/project-provident-law.jpg",
      projectUrl: "https://providentlawllp.ca",
      title: "Provident Law LLP",
      shortDescription: "SEO-ориентированная юридическая платформа для захвата органического спроса и конверсии посетителей в консультации.",
      industry: "Юридические услуги",
      about: "Provident Law LLP — юридическая фирма с несколькими практиками, обслуживающая частных лиц и бизнес в различных правовых вопросах.",
      clientDoes: "Предоставляют комплексные юридические консультации, защиту в суде и структурированные услуги правовой поддержки.",
      problem: "Значительный потенциал органического трафика оставался неиспользованным, а конверсия посетителей в консультации была критически низкой.",
      solution: "Мы реструктурировали контент вокруг поисковых намерений, оптимизировали пути контакта и улучшили обнаружение услуг по всему сайту.",
      built: ["SEO-оптимизированные хабы услуг", "Конверсионные страницы практик", "Мобильно-оптимизированный UX", "Интуитивная архитектура навигации"],
      services: ["SEO-оптимизация", "Веб-разработка", "Информационная архитектура", "Конверсионный UX"],
      duration: "9 месяцев",
      results: [
        { value: "5000+", label: "Привлечённых клиентов" },
        { value: "+90%", label: "Конверсия" },
        { value: "+200%", label: "Органический трафик" },
      ],
    },
    {
      slug: "real-club-nautico-barcelona",
      image: "/project-rcnb.jpg",
      projectUrl: "https://www.rcnb.com/en/",
      title: "Real Club Nautico de Barcelona",
      shortDescription: "Платформа роста членства и бронирований для престижного международного яхт-клуба.",
      industry: "Спорт и гостеприимство",
      about: "RCNB — один из ведущих яхт-клубов Барселоны, управляющий членством, услугами марины и международными парусными мероприятиями.",
      clientDoes: "Предлагают эксклюзивное членство в клубе, бронирование причалов и проводят престижные международные морские соревнования.",
      problem: "Предыдущий сайт не эффективно конвертировал интерес к мероприятиям в членство и бронирования.",
      solution: "Мы перепроектировали пути членов и посетителей с чёткими действиями и контентом, формирующим доверие на всём опыте.",
      built: ["Воронки конверсии членства", "User journeys с фокусом на бронирование", "Архитектура презентации мероприятий", "Mobile-first UX дизайн"],
      services: ["UI/UX Дизайн", "Веб-разработка", "Оптимизация конверсии", "Контент-стратегия"],
      duration: "7 месяцев",
      results: [
        { value: "+85%", label: "Рост членства" },
        { value: "+140%", label: "Объём бронирований" },
        { value: "+160%", label: "Вовлечённость пользователей" },
      ],
    },
  ],
  es: [
    {
      slug: "sviuryst-law-firm",
      image: "/project-law.jpg",
      projectUrl: "https://www.advokats24.com.ua/",
      title: "Despacho de Abogados Sviuryst",
      shortDescription: "Sitio web legal optimizado para conversiones con embudos de consulta simplificados y captación de leads orgánicos.",
      industry: "Servicios Legales",
      about: "Sviuryst es un bufete de abogados de servicio completo que ofrece representación legal, asistencia jurídica urgente y consultoría empresarial.",
      clientDoes: "Ofrecen consultoría legal, representación judicial y servicios contractuales para particulares y clientes corporativos.",
      problem: "El sitio anterior generaba leads de baja calidad, no establecía credibilidad y producía solicitudes de consulta inconsistentes.",
      solution: "Rediseñamos todo el recorrido del usuario en torno a señales de confianza, posicionamiento claro de servicios y reserva de consultas sin fricción.",
      built: ["Páginas de servicios optimizadas para conversión", "Formularios de captación de leads de alta intención", "Diseño responsive mobile-first", "Arquitectura de contenido estructurada para SEO"],
      services: ["Diseño UI/UX", "Desarrollo Web", "Optimización SEO", "Optimización de Tasa de Conversión"],
      duration: "8 meses",
      results: [
        { value: "+230%", label: "Crecimiento de Clientes" },
        { value: "+180%", label: "Volumen de Leads" },
        { value: "+65%", label: "Tasa de Conversión" },
      ],
    },
    {
      slug: "oratorica-language-school",
      image: "/project-education.jpg",
      projectUrl: "https://www.oratorica.ua/",
      title: "Escuela de Idiomas Oratorica",
      shortDescription: "Plataforma de inscripción automatizada que impulsa la captación de estudiantes y escala las ventas de cursos online.",
      industry: "Educación",
      about: "Oratorica es una escuela de idiomas que ofrece programas presenciales y online para adultos y niños.",
      clientDoes: "Ofrecen cursos de idiomas estructurados, programas con instructores y opciones de inscripción flexibles para diversos estudiantes.",
      problem: "El procesamiento manual de inscripciones creaba cuellos de botella, limitando la capacidad de escalar el tráfico de pago y el volumen de solicitudes.",
      solution: "Construimos un sistema de captación totalmente automatizado con autoservicio de inscripción y recorridos de usuario enfocados en la conversión.",
      built: ["Automatización de inscripción de extremo a extremo", "Embudos de landing específicos por curso", "Procesamiento de pagos integrado", "Enrutamiento de leads listo para CRM"],
      services: ["Desarrollo Web", "Automatización de Negocios", "Integración de Pagos", "UX Orientado al Crecimiento"],
      duration: "10 meses",
      results: [
        { value: "EUR 200K+", label: "Ingresos Generados" },
        { value: "+150%", label: "Inscripción de Estudiantes" },
        { value: "+300%", label: "Solicitudes" },
      ],
    },
    {
      slug: "lurssen-yachts",
      image: "/project-luerssen.jpg",
      projectUrl: "https://www.lurssen.com/",
      title: "Lurssen Yachts",
      shortDescription: "Experiencia digital premium que posiciona la marca para la confianza de inversores y la captación de clientes de alto valor.",
      industry: "Yates de Lujo",
      about: "Lurssen es un constructor de superyates de renombre mundial que atiende a individuos de ultra alto patrimonio e inversores institucionales a nivel global.",
      clientDoes: "Diseñan y construyen superyates de lujo a medida para propietarios privados, familias y grupos de inversión.",
      problem: "La presencia digital no comunicaba la exclusividad de la marca ni convertía el tráfico premium en consultas cualificadas.",
      solution: "Creamos una experiencia de storytelling premium con vías de engagement refinadas y mecanismos estratégicos de captación de intención.",
      built: ["Storytelling visual inmersivo", "Arquitectura de contenido enfocada en inversores", "Entrega de medios optimizada", "Vías de consulta premium"],
      services: ["Diseño UI/UX", "Desarrollo Web", "Estrategia de Contenido", "Optimización de Rendimiento"],
      duration: "6 meses",
      results: [
        { value: "+70%", label: "Engagement de Inversores" },
        { value: "+220%", label: "Crecimiento de Tráfico" },
        { value: "+40%", label: "Leads Cualificados" },
      ],
    },
    {
      slug: "sr-aerospace",
      image: "/project-isar-aerospace.jpg",
      projectUrl: "https://isaraerospace.com/",
      title: "SR Aerospace",
      shortDescription: "Plataforma aeroespacial B2B diseñada para el desarrollo de partnerships, credibilidad y crecimiento de inversiones.",
      industry: "Aeroespacial y Defensa",
      about: "SR Aerospace desarrolla sistemas de lanzamiento de próxima generación y mantiene partnerships estratégicos con líderes industriales.",
      clientDoes: "Aseguran financiación de inversión, gestionan partnerships industriales y demuestran capacidades de tecnología de lanzamiento de vanguardia.",
      problem: "La experiencia digital existente no inspiraba confianza en inversores ni convertía efectivamente las oportunidades de partnership.",
      solution: "Reconstruimos la plataforma en torno a puntos de prueba, mensajería estratégica e infraestructura de generación de leads enterprise.",
      built: ["Arquitectura de información optimizada para B2B", "Diseño narrativo de inversión", "Flujos de conversión de partnerships", "Frontend técnico escalable"],
      services: ["Desarrollo Web", "Experiencia de Usuario B2B", "SEO Técnico", "Estrategia Digital"],
      duration: "12 meses",
      results: [
        { value: "$500M+", label: "Inversión Asegurada" },
        { value: "+35%", label: "Acuerdos de Partnership" },
        { value: "+120%", label: "Volumen de Leads B2B" },
      ],
    },
    {
      slug: "provident-law-llp",
      image: "/project-provident-law.jpg",
      projectUrl: "https://providentlawllp.ca",
      title: "Provident Law LLP",
      shortDescription: "Plataforma legal impulsada por SEO construida para capturar demanda orgánica y convertir visitantes en consultas.",
      industry: "Servicios Legales",
      about: "Provident Law LLP es un bufete legal multi-práctica que atiende a individuos y empresas en diversos asuntos legales.",
      clientDoes: "Ofrecen consultoría legal integral, representación en defensa y servicios estructurados de apoyo legal.",
      problem: "Un potencial significativo de tráfico orgánico permanecía sin explotar, y las tasas de conversión de visitante a consulta eran críticamente bajas.",
      solution: "Reestructuramos el contenido en torno a la intención de búsqueda, simplificamos las vías de contacto y mejoramos la descubribilidad de servicios en todo el sitio.",
      built: ["Hubs de servicios optimizados para SEO", "Páginas de áreas de práctica enfocadas en conversión", "Experiencia de usuario optimizada para móvil", "Arquitectura de navegación intuitiva"],
      services: ["Optimización SEO", "Desarrollo Web", "Arquitectura de Información", "UX de Conversión"],
      duration: "9 meses",
      results: [
        { value: "5000+", label: "Clientes Captados" },
        { value: "+90%", label: "Tasa de Conversión" },
        { value: "+200%", label: "Tráfico Orgánico" },
      ],
    },
    {
      slug: "real-club-nautico-barcelona",
      image: "/project-rcnb.jpg",
      projectUrl: "https://www.rcnb.com/en/",
      title: "Real Club Náutico de Barcelona",
      shortDescription: "Plataforma de crecimiento de membresías y reservas para un prestigioso club náutico internacional.",
      industry: "Deportes y Hospitalidad",
      about: "RCNB es uno de los principales clubes náuticos de Barcelona, gestionando membresías, servicios de marina y eventos de navegación internacionales.",
      clientDoes: "Ofrecen membresías exclusivas de club, reservas de amarres y organizan prestigiosas competiciones náuticas internacionales.",
      problem: "El sitio web anterior no convertía eficientemente el interés en eventos en membresías y transacciones de reserva.",
      solution: "Rediseñamos los recorridos de miembros y visitantes con caminos de acción claros y contenido que genera confianza a lo largo de la experiencia.",
      built: ["Embudos de conversión de membresía", "Recorridos de usuario con foco en reservas", "Arquitectura de showcase de eventos", "Diseño UX mobile-first"],
      services: ["Diseño UI/UX", "Desarrollo Web", "Optimización de Conversión", "Estrategia de Contenido"],
      duration: "7 meses",
      results: [
        { value: "+85%", label: "Crecimiento de Membresía" },
        { value: "+140%", label: "Volumen de Reservas" },
        { value: "+160%", label: "Engagement de Usuarios" },
      ],
    },
  ],
  de: [
    {
      slug: "sviuryst-law-firm",
      image: "/project-law.jpg",
      projectUrl: "https://www.advokats24.com.ua/",
      title: "Anwaltskanzlei Sviuryst",
      shortDescription: "Konversionsoptimierte Rechtswebsite mit optimierten Beratungstrichtern und organischer Lead-Erfassung.",
      industry: "Rechtsdienstleistungen",
      about: "Sviuryst ist eine Full-Service-Anwaltskanzlei, die rechtliche Vertretung, dringende Rechtsberatung und Unternehmensberatung anbietet.",
      clientDoes: "Sie bieten Rechtsberatung, Gerichtsvertretung und Vertragsdienstleistungen für Privatpersonen und Unternehmenskunden.",
      problem: "Die vorherige Website generierte minderwertige Leads, schaffte kein Vertrauen und produzierte inkonsistente Beratungsanfragen.",
      solution: "Wir haben die gesamte User Journey um Vertrauenssignale, klare Servicepositionierung und reibungslose Terminbuchung neu gestaltet.",
      built: ["Konversionsoptimierte Serviceseiten", "Lead-Erfassungsformulare mit hoher Kaufabsicht", "Mobile-first responsives Design", "SEO-strukturierte Content-Architektur"],
      services: ["UI/UX Design", "Webentwicklung", "SEO-Optimierung", "Conversion-Rate-Optimierung"],
      duration: "8 Monate",
      results: [
        { value: "+230%", label: "Kundenwachstum" },
        { value: "+180%", label: "Lead-Volumen" },
        { value: "+65%", label: "Konversionsrate" },
      ],
    },
    {
      slug: "oratorica-language-school",
      image: "/project-education.jpg",
      projectUrl: "https://www.oratorica.ua/",
      title: "Sprachschule Oratorica",
      shortDescription: "Automatisierte Anmeldeplattform zur Studentengewinnung und Skalierung von Online-Kursverkäufen.",
      industry: "Bildung",
      about: "Oratorica ist eine Sprachschule, die Online- und Präsenz-Sprachprogramme für Erwachsene und Kinder anbietet.",
      clientDoes: "Sie bieten strukturierte Sprachkurse, von Dozenten geleitete Programme und flexible Anmeldeoptionen für verschiedene Lernende.",
      problem: "Die manuelle Anmeldeverarbeitung schuf Engpässe und begrenzte die Skalierung von bezahltem Traffic und Bewerbungsvolumen.",
      solution: "Wir haben ein vollautomatisiertes Akquisitionssystem mit Selbstbedienungs-Anmeldung und klaren konversionsorientierten User Journeys aufgebaut.",
      built: ["End-to-End-Anmeldungsautomatisierung", "Kursspezifische Landing-Trichter", "Integrierte Zahlungsabwicklung", "CRM-fähiges Lead-Routing"],
      services: ["Webentwicklung", "Geschäftsautomatisierung", "Zahlungsintegration", "Wachstumsorientierte UX"],
      duration: "10 Monate",
      results: [
        { value: "EUR 200K+", label: "Generierter Umsatz" },
        { value: "+150%", label: "Studentenanmeldungen" },
        { value: "+300%", label: "Bewerbungen" },
      ],
    },
    {
      slug: "lurssen-yachts",
      image: "/project-luerssen.jpg",
      projectUrl: "https://www.lurssen.com/",
      title: "Lurssen Yachts",
      shortDescription: "Premium-Digitalerlebnis zur Markenpositionierung für Investorenvertrauen und Akquisition vermögender Kunden.",
      industry: "Luxus-Yachten",
      about: "Lurssen ist ein weltbekannter Superyacht-Hersteller, der ultra-vermögende Privatpersonen und institutionelle Investoren weltweit bedient.",
      clientDoes: "Sie entwerfen und bauen maßgeschneiderte Luxus-Superyachten für private Eigentümer, Familien und Investmentgruppen.",
      problem: "Die digitale Präsenz kommunizierte die Markenexklusivität nicht und konvertierte Premium-Traffic nicht in qualifizierte Anfragen.",
      solution: "Wir haben ein Premium-Storytelling-Erlebnis mit verfeinerten Engagement-Pfaden und strategischen Intent-Erfassungsmechanismen geschaffen.",
      built: ["Immersives visuelles Storytelling", "Investorenorientierte Content-Architektur", "Performance-optimierte Medienbereitstellung", "Premium-Anfragepfade"],
      services: ["UI/UX Design", "Webentwicklung", "Content-Strategie", "Performance-Optimierung"],
      duration: "6 Monate",
      results: [
        { value: "+70%", label: "Investoren-Engagement" },
        { value: "+220%", label: "Traffic-Wachstum" },
        { value: "+40%", label: "Qualifizierte Leads" },
      ],
    },
    {
      slug: "sr-aerospace",
      image: "/project-isar-aerospace.jpg",
      projectUrl: "https://isaraerospace.com/",
      title: "SR Aerospace",
      shortDescription: "B2B-Luft- und Raumfahrtplattform für Partnerschaftsentwicklung, Glaubwürdigkeit und Investitionswachstum.",
      industry: "Luft- und Raumfahrt",
      about: "SR Aerospace entwickelt Startsysteme der nächsten Generation und pflegt strategische Partnerschaften mit Branchenführern.",
      clientDoes: "Sie sichern Investitionsfinanzierung, verwalten Industriepartnerschaften und demonstrieren modernste Starttechnologie-Fähigkeiten.",
      problem: "Das bestehende digitale Erlebnis schuf kein Investorenvertrauen und konvertierte Partnerschaftsmöglichkeiten nicht effektiv.",
      solution: "Wir haben die Plattform um Beweispunkte, strategische Botschaften und Enterprise-Lead-Generierungsinfrastruktur neu aufgebaut.",
      built: ["B2B-optimierte Informationsarchitektur", "Investment-Narrativ-Design", "Partnerschafts-Konversionsflüsse", "Skalierbares technisches Frontend"],
      services: ["Webentwicklung", "B2B User Experience", "Technisches SEO", "Digitale Strategie"],
      duration: "12 Monate",
      results: [
        { value: "$500M+", label: "Gesicherte Investitionen" },
        { value: "+35%", label: "Partnerschaftsabschlüsse" },
        { value: "+120%", label: "B2B-Lead-Volumen" },
      ],
    },
    {
      slug: "provident-law-llp",
      image: "/project-provident-law.jpg",
      projectUrl: "https://providentlawllp.ca",
      title: "Provident Law LLP",
      shortDescription: "SEO-gesteuerte Rechtsplattform zur Erfassung organischer Nachfrage und Konvertierung von Besuchern in Beratungen.",
      industry: "Rechtsdienstleistungen",
      about: "Provident Law LLP ist eine Mehrbereichs-Anwaltskanzlei, die Privatpersonen und Unternehmen in verschiedenen Rechtsfragen betreut.",
      clientDoes: "Sie bieten umfassende Rechtsberatung, Verteidigungsvertretung und strukturierte rechtliche Unterstützungsleistungen.",
      problem: "Erhebliches organisches Traffic-Potenzial blieb ungenutzt, und die Konversionsraten von Besuchern zu Beratungen waren kritisch niedrig.",
      solution: "Wir haben den Content um Suchintention restrukturiert, Kontaktwege optimiert und die Auffindbarkeit von Dienstleistungen verbessert.",
      built: ["SEO-optimierte Service-Hubs", "Konversionsorientierte Praxisbereichsseiten", "Mobiloptimierte Benutzererfahrung", "Intuitive Navigationsarchitektur"],
      services: ["SEO-Optimierung", "Webentwicklung", "Informationsarchitektur", "Konversions-UX"],
      duration: "9 Monate",
      results: [
        { value: "5000+", label: "Gewonnene Kunden" },
        { value: "+90%", label: "Konversionsrate" },
        { value: "+200%", label: "Organischer Traffic" },
      ],
    },
    {
      slug: "real-club-nautico-barcelona",
      image: "/project-rcnb.jpg",
      projectUrl: "https://www.rcnb.com/en/",
      title: "Real Club Nautico de Barcelona",
      shortDescription: "Mitgliedschafts- und Buchungs-Wachstumsplattform für einen prestigeträchtigen internationalen Yachtclub.",
      industry: "Sport & Gastgewerbe",
      about: "RCNB ist einer der führenden Yachtclubs Barcelonas und verwaltet Mitgliedschaften, Marina-Services und internationale Segelveranstaltungen.",
      clientDoes: "Sie bieten exklusive Clubmitgliedschaften, Marina-Liegeplatz-Buchungen und veranstalten prestigeträchtige internationale Nautik-Wettbewerbe.",
      problem: "Die vorherige Website konvertierte Veranstaltungsinteresse nicht effizient in Mitgliedschaften und Buchungstransaktionen.",
      solution: "Wir haben Mitglieder- und Besucher-Journeys mit klaren Handlungspfaden und vertrauensbildendem Content neu gestaltet.",
      built: ["Mitgliedschafts-Konversionstrichter", "Buchungsorientierte User Journeys", "Event-Showcase-Architektur", "Mobile-first UX-Design"],
      services: ["UI/UX Design", "Webentwicklung", "Konversionsoptimierung", "Content-Strategie"],
      duration: "7 Monate",
      results: [
        { value: "+85%", label: "Mitgliedschaftswachstum" },
        { value: "+140%", label: "Buchungsvolumen" },
        { value: "+160%", label: "Benutzer-Engagement" },
      ],
    },
  ],
}

export function getCaseStudies(lang: Language): CaseStudy[] {
  return caseStudies[lang]
}

export function getCaseStudyBySlug(lang: Language, slug: string): CaseStudy | undefined {
  return caseStudies[lang].find((caseStudy) => caseStudy.slug === slug)
}
